variable "region" {}
variable "eks_version" {}
variable "av_zone-1" {}
variable "av_zone-2" {}
variable "vpc_cidr" {}
variable "pub_sub1_cidr" {}
variable "pub_sub2_cidr" {}
variable "priv_sub1_cidr" {}
variable "priv_sub2_cidr" {}
variable "ec2_ssh_key" {}
variable "disk_size" {}
variable "instance_types" {}
variable "cluster_name" {}
variable "enable_oidc" {}
